.TH GL "1" "June 2013" "gl 1.21" ""

.SH NAME
gl \- group listing and group member listing
.SH SYNOPSIS
\fBgl\fR
[\fB-hV\fR]
[\fB-nNrpsv\fR]
[\fIGROUP\fR]
.SH DESCRIPTION
\fBgl\fR is a command line tool which lists all members of the speficied user group.
If no \fIGROUP\fR (name or numerical id) is given, \fBgl\fR lists all groups.
.SH OPTIONS
.TP
.B \-n
Print the names of groups/group members only.
.br
Usually, \fBgl\fR prints their names and IDs.
.TP
.B \-N
Print the IDs of groups/group members only.
.br
Usually, \fBgl\fR prints their names and IDs.
.TP
.B \-r
Raw output:
Separate output with spaces instead of linebreaks.
.TP
.B \-p
When listing group members, list primary members only.
.br
Usually, \fBgl\fR lists primary and secondary members.
.TP
.B \-s
When listing group members, list secondary members only.
.br
Usually, \fBgl\fR lists primary and secondary members.
.TP
.B \-v
Verbose mode:
When listing group members, separate the primary and secondary member list.
Also turns on ansi highlighting for group/member names.
.TP
.B \-h
\fBgl\fR will print a short help summary and exit.
.TP
.B \-V
\fBgl\fR will print its program version and exit.
.SH EXAMPLE
.TP
gl -v staff
Lists all members of the \fBstaff\fR group in a nicely formatted list.
.SH AUTHOR
Maximilian Eul <mle at multinion dot de>
